### ISSUE TITLE
nGrinder uses 100% of CPU all the time

### ISSUE THREAD

**Issue by smiklosovic** [naver/ngrinder#53]
@junoyoon 

Title says it all.

It consumes 100% of one core. I tested in locally and at a remote server as well. Is this a feature or a bug?

**Comment by dexyun** [comment]
@smiklosovic @Mavlarn 

Hi, I had same issue.
I found a reason that it caused by NGrinderControllerStarter class.
If you run as a self executable like that "java -jar ngrinder-controller-3.3.war < /dev/null &", System.in.read() returns always '-1' and loop infinitely.
A temporary solution is that run ngrinder-controller as foreground and do not redirect STDIN.

org.ngrinder.NGrinderControllerStarter.java  line 237
while (System.in.read() != 'q') {
		// Fall through
}

**Comment by smiklosovic** [comment]
@dexyun 

nice catch :), hopefuly guys from nGrinder will repair it, don't you want to submit a PR?
